project:
  type: website
  output-dir: docs
  
website:
  title: "Christina Ladam, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd
      - media.qmd
      - cv.qmd
      
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

