---
title: "Research"
---

Before entering academia, I worked with groups promoting civic engagement. My research agenda is informed by those experiences, and focuses on how people engage with the political system in the United States. In my work I subject normative claims regarding quality civic engagement to empirical scrutiny, offering insights for scholars and practitioners alike. Additionally, I have interests in political discussion, state and local politics, and gender and politics. Working papers are available upon request.

------------------------------------------------------------------------

***Making Deliberation Work: Testing Theories of Deliberation***

Democratic theorists have long argued for deliberation between alternative points of view as a cornerstone of democratic governance. Recent findings suggest that cross-party dialogue can help to mitigate affective polarization. However, deliberation's benefits for democratic society cannot be realized without an optimal design of those institutions. Deliberative practitioners often adhere to a set of guidelines in designing these institutions in service of democratic goals, but many of these decisions have not been tested empirically, posing a problem for both theory and practice alike. In my book project, I put theories of deliberation under empirical scrutiny by testing effects of deliberative design decisions on three key components of the deliberative process: recruiting participants, the deliberative session itself, and the outcomes from deliberation. In doing so, I bridge the theoretical and empirical literatures on deliberation.

------------------------------------------------------------------------

***Politics in Context***

In research with Carey Stapleton (University of Massachusetts), we consider the contextual factors that shift people's perceptions of political content. In one project, we use online survey experiments manipulating the emotion in a political discussion to show the ways that emotion influences the interpretation of those discussions. We use both written and audio experiments to demonstrate that anger is "contagious" --when people observe angry political discussions, they become angry. We have also begun a project to understand how people process political information alone versus in a group. These projects help us to better understand the ways people understand their political environments in the modern media era.

------------------------------------------------------------------------

***Disagreement and Small-group Dynamics***

In work with Anand Sokhey (University of Colorado) and Andrew Therriault, we examine how disagreement in a deliberative setting affects participant behavior and post-deliberation opinions. Using data from a series of deliberative sessions in which participants were randomly assigned to groups, we focus on three dimensions of disagreement---issue-based, partisan, and ideological---and test the effect of encountering disagreement on participants' opinion change after the discussion. Despite fears from extant research regarding the polarizing effects of disagreement, we find no evidence that exposure to disagreement polarizes participants. Using transcripts from the discussions, we extend this idea to see if men and women respond to social influences in similar ways, evaluating how structural factors affect both the quantity and quality of statements made during a small-group discussion. We find that men and women do have different deliberative experiences, with group gender composition and moderator gender playing important roles in conditioning participant behavior.

------------------------------------------------------------------------

***Female Role Models and the Political Representation of Women***

In collaboration with Jeff Harden (University of Notre Dame) and Jason Windett (University of North Carolina--Charlotte), we focus on female political representation and the role that prominent female officeholders play in inspiring other women to enter the political process. In an article in the [*American Journal of Political Science*](https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12351), we find that women holding prominent elected office serve as role models to other women, motivating them to run for office. This highlights the idea that different groups of people have distinct pathways to political participation. I will continue researching how best to incorporate underrepresented groups into the political system.

------------------------------------------------------------------------

***Direct Democracy***

In addition to my work on deliberation and how it may act as a linkage between the mass public and government, I also explore another mechanism for people to influence government: through direct democracy. Specifically, I am interested in better understanding the role of ballot initiatives in the states. In a paper published in the [*Journal of Experimental Political Science*](https://www.cambridge.org/core/journals/journal-of-experimental-political-science/article/abs/does-process-matter-direct-democracy-and-citizens-perceptions-of-laws/588B02074D68B020BB2E017123585293), I use experiments to test whether people feel differently about laws passed through ballot initiative as opposed to the legislative process. I find that although people do view the ballot initiative process as a valid and fair lawmaking institution, their evaluations of laws are not influenced by the way in those laws are passed. Ultimately, people tend to evaluate the law itself, regardless of the process used to pass the law. In other work, co-authored with Joe Zamadics, we consider how a state's institutional context dictating ballot initiative access affects the likelihood of passage. Using a new dataset of all popularly initiated ballot measures from 2000--2020, we find that more stringent rules for ballot access create more support for measures during the voting phase.

------------------------------------------------------------------------

***Modern Polling Modalities***

A recent research interest stems from my work with the Nevada Election Survey Project. With Jeremy Gelman (UNR), I have fielded surveys using several different modalities: opt-in internet samples, a direct mailer, and Facebook-based recruiting. We can speak to these different modes of survey recruitment and their trade-offs. We are set to present the findings of this research at the annual meeting of the Midwest Political Science Association in 2023.
