---
title: "Teaching"
---

I have ten years of teaching experience, and teach classes in American politics and methodology at both the undergraduate and graduate levels. In the 2021-2022 academic year, I completed the [Community Engaged Teaching](https://www.unr.edu/service-learning/faculty-information/certificate) program at UNR. I am a Faculty Fellow with the [Educational Network for Active Civic Transformation (ENACT)](https://www.brandeis.edu/ethics/enact/), at Brandeis University. Using these trainings, I have developed a service learning course on state politics where students lobby members of the state legislature on current legislation under consideration.

------------------------------------------------------------------------

## Course Offerings

-   American Politics: Process and Behavior

-   Constitutional Law: Separation of Powers and Federalism

-   Constituttional Law: Civil Rights and Liberties

-   Gateway to the Social Sciences

-   Political Campaigns and Elections

-   Public Opinion and Political Behavior

-   Research Methods in Political Science (graduate)

-   Survey of State and Local Governments

-   Urban Politics
